server:
  port: 8082
  servlet:
    context-path: /lev1

spring:
  redis:
    host: 192.168.31.76
    port: 6379
  rabbitmq:
    host: 192.168.31.76
    port: 5672
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.31.76:3306/jdbc?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
#    schema:
#      - classpath:sql/schema.sql
#    initialization-mode:

logging:
  level:
    com:
      lev1:
        springboot:
          mapper: debug
